In [ ]:
# 理解 super 函数的功效
def add(a=None, b=None):
    super().add(a=1,b=2)
    


In [3]:
from copy import copy
# 测试 copy class
class data():
    class obs_scales():
        a=1
        b=2

obs_scales = copy(data.obs_scales)
print(obs_scales.a)
# 结论： copy结果就相当于原模原样的一个类，可以调用其中的数据

1


In [14]:
dict = {}
list = []
list.append(123)
# dict.append('a', 10)
dict['b']=11
print(dict)
print(list)
# 结论：字典不能append，列表可以

{'b': 11}
[123]


In [22]:
# 测试nonzero函数
import numpy as np
import torch
buffers=np.array([[0,8,0],[7,0,0],[-5,0,1]])
print(buffers)
buff=torch.from_numpy(buffers)
# buffers.nonzero(as_tuple=False).flatten()
print(buff.nonzero(as_tuple=False).flatten())
print(buff.nonzero(as_tuple=False))
print()

buffers1=np.array([0,8,0,7,0,0-5,0,1])
print(buffers1)
buff1=torch.from_numpy(buffers1)
# buffers.nonzero(as_tuple=False).flatten()
print(buff1.nonzero(as_tuple=False).flatten())
print(buff1.nonzero(as_tuple=False))
# 结论：转换成torch张量才能用flatten，按向量维数返回标号；如果是一维的最好，用完flatten就直接对应一维标号；

[[ 0  8  0]
 [ 7  0  0]
 [-5  0  1]]
tensor([0, 1, 1, 0, 2, 0, 2, 2])
tensor([[0, 1],
        [1, 0],
        [2, 0],
        [2, 2]])

[ 0  8  0  7  0 -5  0  1]
tensor([1, 3, 5, 7])
tensor([[1],
        [3],
        [5],
        [7]])
